server:
  port: 8081
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-abc123.auth0.com/



  datasource:
    url: "jdbc:sqlite:C:/Users/Rosema/Documents/incautasLocal.db"
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: info
    org.springframework: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
