server:
  port: 8081
  servlet:
    context-path: / # Asegura que el contexto base sea accesible directamente

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    url: "jdbc:sqlite:C:/Users/Rosema/Documents/incautasLocal.db" # Configura tu conexión SQLite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update # Actualiza automáticamente el esquema (cuidado en producción)
    show-sql: true # Muestra las consultas SQL en los logs
    properties:
      hibernate.dialect: org.hibernate.community.dialect.SQLiteDialect # Dialecto para SQLite
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Permite mayor flexibilidad en las rutas

logging:
  level:
    org:
      springframework:
        security: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*" # Habilita todos los endpoints del Actuator (útil para depuración)
